name: Lint

# Github actions for Turborepos
# ref: https://turborepo.com/docs/guides/ci-vendors/github-actions

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize"]

  workflow_dispatch:

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    # Turborepo remote cache
    # ref: https://turborepo.com/docs/guides/ci-vendors/github-actions#remote-caching

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check types
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
        run: pnpm build
